#yml语法要求yml文件的value和冒号":"之间要有一个空格
#server配置服务器信息
server:
  port: 8080
  #上下文路径
  context-path: /

yml:
  key: yml-value-dev

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #db1
    db1:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
      username: scott
      password: tiger
    #db2
    db2:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@28.163.0.27:1521:devxfkhdb
      username: xfkh
      password: liulaoshi#haoren
    #db3
    db3:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/boot1?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root